### ISSUE TITLE
admin UI

### ISSUE THREAD

**Issue by goodsheet** [skyverge/woocommerce-sage-erp-connector#1]
Hi,

I have installed this plugin and do not see either the Sage ERP status column in Woocommerce orders, nor is the "Export to Sage ERP" order action available.  Any help with updating the plugin is greatly appreciated!

Thank you!

**Comment by maxrice** [comment]
@goodsheet sorry for the delayed response, not sure why I didn't see this notification.

Can you double-check that you have API info (endpoint, username, password) and other info (company code, division no, and price level) populated? The status column/export buttons don't display unless all those are filled out :smiley_cat:

**Comment by goodsheet** [comment]
Hello and thank you for getting back to me.

The only item not populated is the price level as I’m unsure as to what value that could/should be (documentation on github states that this is optional).  Can you provide some insight into that?

Thank you!
Jacob
On May 6, 2015, at 9:32 PM, Max Rice <notifications@github.com<mailto:notifications@github.com>> wrote:


@goodsheet<https://github.com/goodsheet> sorry for the delayed response, not sure why I didn't see this notification.

Can you double-check that you have API info (endpoint, username, password) and other info (company code, division no, and price level) populated? The status column/export buttons don't display unless all those are filled out [:smiley_cat:]

—
Reply to this email directly or view it on GitHub<https://github.com/skyverge/woocommerce-sage-erp-connector/issues/1#issuecomment-99683460>.



Jacob Romberg
Web Developer


Good Sheet
1325 N 59th Ave W
Duluth, MN 55807<http://goodsheet.co>
TEL:    218-336-8581<tel:218-336-8581>

**Comment by goodsheet** [comment]
Hello Max,

After entering “100” in the price level (just as a test) the export to Sage functionality now appears.  One other question I have is in relation to the API endpoint and error message received.  Do you suspect that from the error message that some changes in the <xsd: import schemaLocation=""/> within eBusinessWebServices would be effective/needed?

--------------------------------------------------------------------------------------------------------------------------
API Endpoint tried:
https://orders.lolldesigns.com/eBusinessWebServices/MasBasicWsdl.svc?wsdl

Error:
Export Failure - Order 12947 (ERP Sales Order No: N/A), Message : SOAP-ERROR: Parsing Schema: can't import schema from 'https://epicmas200.hawksboots.int/eBusinessWebServices/MasBasicWsdl.svc?xsd=xsd0' (N/A)
Order failed export to Sage ERP.

--------------------------------------------------------------------------------------------------------------------------
Thank you for any input/support you can provide!
Jacob



Jacob Romberg
Web Developer


Good Sheet
1325 N 59th Ave W
Duluth, MN 55807<http://goodsheet.co>
TEL:    218-336-8581<tel:218-336-8581>

**Comment by maxrice** [comment]
Your eBusiness Web Services API is configured improperly, it's using the local hostname (`https://epicmas200.hawksboots.int/eBusinessWebServices/MasBasicWsdl.svc?xsd=xsd0`) instead of the public hostname (`https://orders.lolldesigns.com/eBusinessWebServices/MasBasicWsdl.svc?wsdl`) which is why it says "can't import schema".

unfortunately I can't recall exactly what the fix is but I believe it's related to the IIS config for the add-on.

**Comment by goodsheet** [comment]
Great, thanks!  I changed IIS host headers on epicmas200 using IIS Metabase Explorer - updated EPICMAS200/LM/W3SVC/1 ID: 2021 SecureBindings from: :443: to: :443:orders.lolldesigns.com<http://orders.lolldesigns.com> and restarted IIS.

I changed the PriceLevel from 100 to 1 due to the following error (:: Price Level is greater that 1 character(s)).

Now receiving this error regarding Tax Schedule is required (Could not write to SO_SalesOrder_Bus):
Export Failure - Order 12950 (ERP Sales Order No: 0034856), Message : Could not write to SO_SalesOrder_Bus: The Tax Schedule is required. (0 : The Tax Schedule is required.Š)
Order failed export to Sage ERP.

Is there somewhere that I need to configure/map the fields so that data matches up between a woocommerce order and the eBusinessWebServices installed on Sage MAS?

Do I accomplish this by tweeking/modifying the plugins php file(s)?  I just can’t find any documentation on this!

Thanks again for all of your help!
On May 7, 2015, at 11:20 AM, Max Rice <notifications@github.com<mailto:notifications@github.com>> wrote:


Your eBusiness Web Services API is configured improperly, it's using the local hostname (https://epicmas200.hawksboots.int/eBusinessWebServices/MasBasicWsdl.svc?xsd=xsd0) instead of the public hostname (https://orders.lolldesigns.com/eBusinessWebServices/MasBasicWsdl.svc?wsdl) which is why it says "can't import schema".

unfortunately I can't recall exactly what the fix is but I believe it's related to the IIS config for the add-on.

—
Reply to this email directly or view it on GitHub<https://github.com/skyverge/woocommerce-sage-erp-connector/issues/1#issuecomment-99926462>.



Jacob Romberg
Web Developer


Good Sheet
1325 N 59th Ave W
Duluth, MN 55807<http://goodsheet.co>
TEL:    218-336-8581<tel:218-336-8581>

**Comment by maxrice** [comment]
Ah yeah, that sounds familiar. If the Sage install has sales tax set, you need to define the tax schedule for the sales order. You can edit the plugin around [here](https://github.com/skyverge/woocommerce-sage-erp-connector/blob/master/classes/class-wc-sage-erp-connector-exporter.php#L246) to add that (something like `$sales_order->TaxSchedule` I think), or use the filter [here](https://github.com/skyverge/woocommerce-sage-erp-connector/blob/master/classes/class-wc-sage-erp-connector-exporter.php#L299) to modify the sales order in an upgrade-safe manner.

**Comment by goodsheet** [comment]
just add "$sales_order->TaxSchedule;" ?

**Comment by maxrice** [comment]
yeah I think that will work

**Comment by goodsheet** [comment]
That didn't work, same error.  I tried turning off "testing mode" too.  Hmmm?  We are using standard tax rates in woocommerce.  Any other thoughts?  Would I need to assign the TaxSchedule value to a variable to be passed to MAS?

**Comment by goodsheet** [comment]
I have determined what the current Sage MAS tax schedule codes are.  Below is a one to one match between Sage MAS codes and the Woocommerce Tax Rates for the Standard class, I'm just not sure how to code this into the plugin.  Any help would be greatly appreciated!
SAGE MAS Tax Schedule List (CODE - Description) || WOOCOMMERCE Standard Tax Rates (Tax Name):
NONTAX - Nontaxable Tax Schedule    ||  no tax present in woocommerce order (no actual tax charged/generated)
MN - Minnesota General Sales Tax    ||  MN State Tax (6.875%)
MN ST LOU - St Louis County MN      ||  MN + County Tax (7.375%)
MN DLTH - Minnesota Duluth          ||  MN + County + Duluth Tax (8.375%)
GST - GST Canada                    ||  GST (5.0%)
ONT-CA - Ontario Canada             ||  HST (13.0%)

![woocommerce-tax-rates](https://cloud.githubusercontent.com/assets/11858611/7546232/38dfd49a-f5a1-11e4-8328-e7330f0fa18b.png)
![sage-mas-tax-schedule-list](https://cloud.githubusercontent.com/assets/11858611/7546233/38e2240c-f5a1-11e4-8656-8d9690e94bc8.png)

**Comment by maxrice** [comment]
The error suggests it needs to be set on the sales order so maybe test with something like:

`$sales_order->TaxSchedule = 'GST'`

The [schema](https://orders.lolldesigns.com/eBusinessWebServices/MasBasicWsdl.svc?xsd=xsd0) says that's accurate, search for "Tax Schedule"

**Comment by goodsheet** [comment]
Hi again!  After using $sales_order->TaxSchedule = 'NONTAX';  because the particular single order I exported had no tax values, it exported.  However not all of the data was exported (customer billing and shipping address, shipping amounts, etc); or not all was imported.  Perhaps the field mappings are incorrect.  I'm guessing that I will need to modify the plugin to map the woocommerce orders data to eBusinessWebServices?

**Comment by maxrice** [comment]
I believe billing/shipping addresses might be pulled from the customer record instead of the sales order. unfortunately with Sage it's not really well documented what does what. You can download the [API guide](http://cl.ly/2B3Z3n32320u) which gives you a bit more info but my recommendation is to just experiment :)

Also, while modifying the plugin is the easiest way to test, in production you'll want to make use of the filters in the plugin to make your customization so that you can upgrade the connector later without worrying about losing the customizations you've made.
