### ISSUE TITLE
Help with identifying fields

### ISSUE THREAD

**Issue by Vinsanity** [skyverge/woocommerce-sage-erp-connector#10]
Hello, 
I was wondering if you happen to know if the "Cust PO" field within SAGE is a $sales_order field or a $customer field. I've tried setting several combinations both within the arrays and cannot get it to populate. I've tried `$sales_order->CustPO, $sales_order->CustomerPO, $sales_order->PONumber, $sales_order->PurchaseOrderNo` and a few others and all of them in $customer-> as well. I'm also not able to locate anything within the SAGE documentation giving a list of standard fields for mapping.

Any help would be greatly appreciated.

Thanks.

**Comment by maxrice** [comment]
Just looked at the custom plugins we've built and it looks like PO number is a sales order field. Try `$sales_order->CustomerPONo`. Depending on your version/setup, it may be a custom field, in which case you can try something like `$customer->_CustomFields = array( 'UDF_SALE_CHANNEL$' => 'C - Consumer' );` where `UDF_*` is the custom field. If that fails, take a look at the raw WSD that the Sage endpoint gives you and see if any of the fields are listed there. Unfortunately the Sage documentation on this API is pretty much non-existent these days so it's all a matter of trial/error. good luck!

**Comment by Vinsanity** [comment]
Worked perfectly! Thanks for the quick response @maxrice. 

I too found that the documentation on this is extremely sparse so I appreciate your help and knowledge on this. I didn't even think about taking a look at the raw WSD from the endpoint. I'm going to explore that too to just to document a list for our own use. 

Thanks again.
