### ISSUE TITLE
Sage ERP 2017 compatibility

### ISSUE THREAD

**Issue by cdCorey** [skyverge/woocommerce-sage-erp-connector#15]
Does anyone know if this is compatible with Sage ERP 2017?

**Comment by maxrice** [comment]
Nope, I don't believe this is compatible with Sage ERP 2017, only Sage 100 which has the eBusiness Web Services module available. sorry!

**Comment by F3L1X79** [comment]
Same question goes for Sage X3. Any thoughts? 
Thanks in advance.

**Comment by maxrice** [comment]
@F3L1X79 no, this requires the eBusiness Web Services module which X3 doesn't have, AFAIK.
