### ISSUE TITLE
How does one view th XML output of a request?

### ISSUE THREAD

**Issue by apasho** [skyverge/woocommerce-sage-erp-connector#16]
I tried doing this but it does not work:

echo $wc_sage_erp_connector->api->client->__getLastRequest();

**Comment by maxrice** [comment]
try using `htmlentities()` since the XML is hidden by the browser, see http://php.net/manual/en/soapclient.getlastrequest.php

**Comment by apasho** [comment]
Actually, this does not address the issue. in class-wc-sage-erp-connector-exporter.php, in the function export_order(), in 'catch ( SoapFault $e )' block, I have added,

if(isset($wc_sage_erp_connector->api->client))
       error_log("Last Request " . $wc_sage_erp_connector->api->client->__getLastRequest());
else
      error_log("client not set");

I have made $api and $client public. Since the information is written to the debug.log, I do not think htmlentities() is needed. The result I get is 'client not set'. Access to $client is the problem. Do you have any suggestions?

**Comment by maxrice** [comment]
what's the exception message for SoapFault? sounds like there's something going wrong before the client is setup and thus it's not available when inside the try/catch block.

**Comment by apasho** [comment]
The error is Export Failure - Order 145101 (ERP Sales Order No: N/A), Message : SOAP-ERROR: Parsing WSDL: Couldn't load from 'https://...' : failed to load external entity "https:..." (N/A)
Order failed export to Sage ERP.
Now I'm looking into some server settings that may be preventing reading the file.

**Comment by maxrice** [comment]
Ah, yeah make sure that the server you're running the plugin on can access the WSDL from the Sage server. It takes some configuring on the IIS side to make it publicly accessible, but once that's working you should be good to go.
