### ISSUE TITLE
SOAP-ERROR: Parsing WSDL

### ISSUE THREAD

**Issue by WebGriffinWink** [skyverge/woocommerce-sage-erp-connector#2]
I'm getting an error when exporting to Sage saying: Export Failure - Order 9083, Message: SOAP-ERROR: Parsing WSDL: Couldn't load from "url": failed to load exernal entity "url" (N/A) 
Order failed export to Sage ERP.

**Comment by maxrice** [comment]
Make sure your API endpoint is publicly accessible, pasting the URL into a browser should show render an XML looking document.
