### ISSUE TITLE
Connecting to Host

### ISSUE THREAD

**Issue by WebGriffinWink** [skyverge/woocommerce-sage-erp-connector#3]
Hi there,
Thank you for helping resolve the last issue, what you said did the trick. I have a new issue now, which is the following error message:
Export Failure - Order 9102 (ERP Sales Order No: N/A), Message : Could not connect to host (N/A)
Order failed export to Sage ERP.

Any ideas?
Thanks,
Austin

**Comment by maxrice** [comment]
This is usually as a result of a firewall or similar blocking the incoming connection from the website -- check the logs on the ERP server side and see what connections are being allowed :)
