### ISSUE TITLE
New Error Message

### ISSUE THREAD

**Issue by WebGriffinWink** [skyverge/woocommerce-sage-erp-connector#4]
Hi, I apologize to keep bugging you with errors, but I ran across another one:

Export Failure - Order 9102 (ERP Sales Order No: N/A), Message : Not Found (N/A)
Order failed export to Sage ERP.

Any ideas on what this could be? 
Thank you,
Austin

**Comment by WebGriffinWink** [comment]
If need be, I can provide temporary FTP/backend access if that helps at all?

Thanks again.

**Comment by WebGriffinWink** [comment]
I also received this error when attempting to export:

Export Failure - Order 9102 (ERP Sales Order No: N/A), Message : Function ("GetCustomer") is not a valid method for this service (N/A)
Order failed export to Sage ERP.

**Comment by WebGriffinWink** [comment]
If I need to submit payment of some sort for a that kind of a service, I can do that.

**Comment by maxrice** [comment]
These error messages are because the customer you're trying to import the sales order under does not exist.
