### ISSUE TITLE
Cannot load woocommerce.

### ISSUE THREAD

**Issue by xanadustc** [skyverge/woocommerce-sage-erp-connector#5]
Hi there,

We are trying to set up a new site with your connector but every time when I go to Configure it gives an error Cannot load WooCommerce.  Any help would be appreciated.

WP: 4.3.1
WC: 2.4.7
WCSerpC: 1.3

Thanks

**Comment by maxrice** [comment]
Can you post a screenshot of the error you're seeing here and re-open if you're still having an issue? thanks :)
