### ISSUE TITLE
update_sales_order doesn't seem to work

### ISSUE THREAD

**Issue by nikolov-tmw** [skyverge/woocommerce-sage-erp-connector#6]
Hi there, I'm using your plugin and it works great(whatever data is not there is really easy to add with the filters).

I had to update a sales order once it was created in Sage(for some reason some properties were getting overwritten during creation) and so I used this code:

    global $wc_sage_erp_connector;

    $sales_order = (object) array(
    	'SalesOrderNo' => $sales_order_no,
    	'CheckNoForDeposit' => $last_four,
    	'FreightAmt' => $freight_amount,
    );

    require_once( $wc_sage_erp_connector->get_plugin_path() . '/classes/class-wc-sage-erp-connector-api.php' );

    // init API
    $api = new WC_Sage_ERP_Connector_API( $wc_sage_erp_connector->integration->api_endpoint,$wc_sage_erp_connector->integration->api_username, $wc_sage_erp_connector->integration->api_password, $wc_sage_erp_connector->integration->company_code );

    try {
    	$api->update_sales_order( $sales_order_no, $sales_order );
    } catch (SoapFault $e) {
    	error_log( 'Error updating FreightAmt for SalesOrder ' . $sales_order_no . '. Error is: ' . $e->getMessage() );
    }

However it gave me the following error: `The salesOrder parameter is null.`. So I went in `class-wc-sage-erp-connector-api.php` and changed the `update_sales_order()` function to this:

    $this->get_connection()->UpdateSalesOrder( array(
    		'logon'        => $this->get_logon(),
    		'companyCode'  => $this->company_code,
    		'salesOrderNo' => $sales_order_no,
    		'salesOrder'   => $value,
    	)
    );

And everything works properly now.

Do you want me to create a PR for this bug? With the holidays it might take me a few days to get it submitted, but it won't be a problem for me.

**Comment by maxrice** [comment]
thanks for reporting this @nikolov-tmw, would love a PR for this fix :)

**Comment by nikolov-tmw** [comment]
Hey @maxrice - I've created the PR for this. :smiley:

**Comment by maxrice** [comment]
thanks @nikolov-tmw!
